<?php

return [
    'age_min' => 18,
    'age_max_regular' => 25,
    'age_max_tradesmen' => 27,
    'age_max_officer' => 30,
    'height_min_male' => 1.65,
    'height_min_female' => 1.58,
    'nationality' => 'Ghanaian',
    'voucher_costs' => [
        'regular' => 50,
        'tradesmen' => 100,
        'officer' => 200,
    ],
    'categories' => ['regular', 'tradesmen', 'officer'],
    'regions' => ['Ahafo', 'Ashanti', 'Bono', 'Bono East', 'Central', 'Eastern', 'Greater Accra', 'Northern', 'North East', 'Oti', 'Savannah', 'Upper East', 'Upper West', 'Volta', 'Western', 'Western North'],
    'health_conditions' => ['Asthma', 'Diabetes', 'Hypertension', 'Epilepsy', 'Hearing Loss', 'Vision Impairment'],
    'education_levels' => ['SHS', 'Diploma', 'HND', 'Degree', 'Masters', 'PhD'],
    'screening_types' => ['medical', 'fitness', 'interview'],
    'application_stages' => [
        'registered',
        'draft',
        'submitted',
        'documents_verified',
        'eligibility_passed',
        'shortlisted',
        'appointment_scheduled',
        'screening_completed',
        'final_decision_pending',
        'selected',
        'recruited',
        'reserve',
    ],
    'statuses' => [
        'registered' => ['label' => 'Registered', 'color' => 'bg-gray-100 text-gray-500'],
        'draft' => ['label' => 'Draft', 'color' => 'bg-gray-100 text-gray-500'],
        'submitted' => ['label' => 'Submitted', 'color' => 'bg-blue-100 text-blue-700'],
        'documents_verified' => ['label' => 'Docs Verified', 'color' => 'bg-teal-100 text-teal-700'],
        'eligibility_passed' => ['label' => 'Eligible', 'color' => 'bg-green-100 text-green-700'],
        'eligibility_failed' => ['label' => 'Ineligible', 'color' => 'bg-red-100 text-red-700'],
        'shortlisted' => ['label' => 'Shortlisted', 'color' => 'bg-amber-100 text-amber-700'],
        'appointment_scheduled' => ['label' => 'Appointment Set', 'color' => 'bg-indigo-100 text-indigo-700'],
        'screening_completed' => ['label' => 'Screened', 'color' => 'bg-emerald-100 text-emerald-700'],
        'final_decision_pending' => ['label' => 'Decision Pending', 'color' => 'bg-amber-100 text-amber-700'],
        'selected' => ['label' => 'Selected', 'color' => 'bg-green-100 text-green-700'],
        'recruited' => ['label' => 'Recruited', 'color' => 'bg-emerald-100 text-emerald-700'],
        'rejected' => ['label' => 'Rejected', 'color' => 'bg-red-100 text-red-700'],
        'disqualified' => ['label' => 'Disqualified', 'color' => 'bg-red-100 text-red-700'],
        'reserve' => ['label' => 'Reserve List', 'color' => 'bg-blue-100 text-blue-700'],
    ],
    'document_statuses' => [
        'pending' => ['label' => 'Pending', 'color' => 'bg-yellow-100 text-yellow-700'],
        'verified' => ['label' => 'Verified', 'color' => 'bg-green-100 text-green-700'],
        'rejected' => ['label' => 'Rejected', 'color' => 'bg-red-100 text-red-700'],
        'needs_review' => ['label' => 'Needs Review', 'color' => 'bg-orange-100 text-orange-700'],
    ],
    'cycle_statuses' => [
        'draft' => ['label' => 'Draft', 'color' => 'bg-gray-100 text-gray-600'],
        'active' => ['label' => 'Active', 'color' => 'bg-green-100 text-green-700'],
        'closed' => ['label' => 'Closed', 'color' => 'bg-red-100 text-red-700'],
        'archived' => ['label' => 'Archived', 'color' => 'bg-gray-200 text-gray-500'],
    ],
    'appointment_statuses' => [
        'scheduled' => ['label' => 'Scheduled', 'color' => 'bg-blue-100 text-blue-700'],
        'confirmed' => ['label' => 'Confirmed', 'color' => 'bg-green-100 text-green-700'],
        'checked_in' => ['label' => 'Checked In', 'color' => 'bg-teal-100 text-teal-700'],
        'attended' => ['label' => 'Attended', 'color' => 'bg-gray-100 text-gray-700'],
        'missed' => ['label' => 'Missed', 'color' => 'bg-red-100 text-red-700'],
        'completed' => ['label' => 'Completed', 'color' => 'bg-green-100 text-green-700'],
        'pending' => ['label' => 'Pending', 'color' => 'bg-yellow-100 text-yellow-700'],
    ],
    'screening_results' => [
        'fit' => ['label' => 'Fit', 'color' => 'bg-green-100 text-green-700'],
        'unfit' => ['label' => 'Unfit', 'color' => 'bg-red-100 text-red-700'],
        'pass' => ['label' => 'Pass', 'color' => 'bg-green-100 text-green-700'],
        'fail' => ['label' => 'Fail', 'color' => 'bg-red-100 text-red-700'],
        'recommended' => ['label' => 'Recommended', 'color' => 'bg-green-100 text-green-700'],
        'not_recommended' => ['label' => 'Not Recommended', 'color' => 'bg-red-100 text-red-700'],
        'pending' => ['label' => 'Pending', 'color' => 'bg-yellow-100 text-yellow-700'],
        'in_progress' => ['label' => 'In Progress', 'color' => 'bg-yellow-100 text-yellow-700'],
    ],

    'scheduling' => [
        'default_date' => env('SCHEDULE_DEFAULT_DATE', 'next_weekday'),
        'default_time' => env('SCHEDULE_DEFAULT_TIME', '08:00'),
        'daily_capacity' => (int) env('SCHEDULE_DAILY_CAPACITY', 50),
    ],

    'scoring_weights' => [
        'medical' => 0.40,
        'interview' => 0.30,
        'fitness' => 0.20,
        'eligibility' => 0.10,
    ],

    'auto_recruit' => [
        'enabled' => env('AUTO_RECRUIT_ENABLED', false),
        'enrollment_delay_days' => (int) env('AUTO_RECRUIT_DELAY_DAYS', 14),
        'default_training_battalion' => env('DEFAULT_TRAINING_BATTALION', 'GAF Training Depot'),
    ],

    'reserve_ratio' => 0.20,

    'auto_promote_reserve' => env('AUTO_PROMOTE_RESERVE', false),

    'auto_final_decision' => env('AUTO_FINAL_DECISION', true),
];
